### ISSUE TITLE
LDP in Standard

### ISSUE THREAD

**Issue by simonLouvet** [datafoodconsortium/dfc-prototype-V2#15]
**Is your feature request related to a problem? Please describe.**
LDP not included in Standard and data flow example

**Describe the solution you'd like**
LDP included in Standard and data flow example

**Describe alternatives you've considered**
not included it

**Additional context**
https://www.w3.org/TR/ldp/

**Comment by myriamboure** [comment]
Is this done with what you added to the document ? I made the integration in the Gitbook so if that was the acceptance test we can say it's done, if that was what this issue is about.
