### ISSUE TITLE
As a surfer, I can link products one to another in batch

### ISSUE THREAD

**Issue by RachL** [datafoodconsortium/dfc-prototype-V2#22]
**Description**
The purpose of this issue is to be able to link similar products from different platforms in batch.

**Acceptance Tests**
1. Go to http://datafoodconsortium.org/dfc-prototype-V2/public/#/x-easyui
2. The catalog menu has a dropdown where I can select a sub-menu in order to link the products from the last import one to another.
3. On this page, I am asked to review products one by one and decide if they need to be linked to an existing product in the database or not (see mockups). **Only one product can be linked to another one, not more**. Selecting a product **OR** selecting the checkbox is mandatory.
4. When all products have been reviewed, I can see a link on their page (see issue #31 )

**Mockups**

![image](https://user-images.githubusercontent.com/6525576/60452082-110cf000-9c2e-11e9-932a-fbeaf7fe1c84.png)

![image](https://user-images.githubusercontent.com/6525576/58813930-13772c80-8625-11e9-8270-61bc4a9f52d7.png)

Link to full mockups workflow: https://drive.google.com/drive/u/0/folders/1at-12cgVrdtua871AtDJfOCjaZ2Wl1hF

**Comment by myriamboure** [comment]
Great ! Just a small suggestion about the phrasing "Ce produit existe-il déjà sur le catalogue commun ? Peut-être l'avez-vous déjà importé d'une autre plateforme ?" Just to be a bit more explicit, I find strange to say that a product is on the universal catalog for another platform. Else looks really good and clear @RachL !

**Comment by RachL** [comment]
@myriamboure on slack I think @simonLouvet suggested to move the question to the bottom of the screen as a checkbox "je n'ai pas trouvé mon produit". I guess this is the right solution if the producer doesn't already know which product he is selling in both platform. What do you think?

**Comment by myriamboure** [comment]
Yes I agree with that suggestion as well. I still keep mine, both are compatible I think ;-)

**Comment by RachL** [comment]
@myriamboure @simonLouvet I've updated the mockups. Sorry for the delay. I liked your suggestion Simon on how we could reduce the number of clicks by switching directly to the next product when selecting "je n'ai pas trouvé le produit" or on a suggested product. Not sure if it would play well with the search, but we can try it for the two checkboxes and see how it goes when using it. I would however keep the possibility to go back to the previous product in case I missclicked.

**Comment by myriamboure** [comment]
if you select the checkbox, it creates a new product in the common catalog then, right ?
If I click "cancel" what happens ? Does all the import stops ? This is confusing to me. Shall we have a "previous" button instead then ? And a "stop import" (the products already imported stay) or "cancel import (the new products created are removed).

**Comment by RachL** [comment]
@myriamboure First, just to be sure we are on the same page: even if you link a product to another, you do import the product. Just in a different way.
Then I guess it is up to @simonLouvet to tell us which solution is the easiest for now: if we import one by one or in batch at the end. However if we import one by one, I wouldn't add a previous button. This seems really complex to handle: you would need to delete a product and re-create it. I wouldn't go that far yet.
We can rename the cancel button as "stoper l'import". But both have the same result : you are redirected to the catalog page. We can of course add an "are you sure" modal before doing so. Again I wouldn't go up to delete in bulk unless Simon's says it is really easy to do it here.
