### ISSUE TITLE
Find a producer common to LRQDO, Cagette and Panier Local

### ISSUE THREAD

**Issue by RachL** [datafoodconsortium/dfc-prototype-V2#23]
**Description**
We need to find a producer common to LRQDO, Cagette and Panier Local to have a large set of data for the prototype.

**Comment by nclavaud** [comment]
Found _Le vivier des saveurs_ which might be a good (and the only?) candidate:
https://laruchequiditoui.fr/fr/producers/5436/
http://www.levivierdessaveurs.fr/bv.stp?ACTION=ACCUEIL&CAT=produits

**Comment by nclavaud** [comment]
API endpoint for this producer at LRQDO:
https://api.thefoodassembly.com/dfc/catalog/5436
