### ISSUE TITLE
API endpoints for the common producer

### ISSUE THREAD

**Issue by RachL** [datafoodconsortium/dfc-prototype-V2#26]
**Description**
Now that a common producer has been found in #23 all 3 platforms need to provides API endpoints for this producer.

LRQDO already did it here:
https://api.thefoodassembly.com/dfc/catalog/5436

Panier Local and Cagette are missing.

**Comment by myriamboure** [comment]
From François on Slack :
"'ai du recoder un peu pour avoir les infos ( je vous épargne les détails )
Babelicot https://app.cagette.net/api/pro/dfc/contract/7027
viver des saveurs https://app.cagette.net/api/pro/dfc/contract/10483
( jai pu finalement bidouiller pour avoir leurs produits comme si ils avaient un catalogue )"

Ping @RachL @simonLouvet things can move on on that side now :-)
