### ISSUE TITLE
Bring the "edit" button to main catalog page

### ISSUE THREAD

**Issue by RachL** [datafoodconsortium/dfc-prototype-V2#34]
**Description**
Today, we can link products or access a product page on the non consolidated list of product.

The purpose of this issue is to bring this action to the main catalog page. 

**Acceptance Tests**
1. Go to http://185.25.192.252:8080/ui/#/x-import-catalog
2. On this page a new column shows an "edit" link (same as currently on non consolidated page)

**Comment by simonLouvet** [comment]
A edit button for each catalog line navigate to catalog for.  User can edit name and unconsolidate an import on catalog form.
