### ISSUE TITLE
Create new URL with OIDC header

### ISSUE THREAD

**Issue by RachL** [datafoodconsortium/dfc-prototype-V2#41]
**Description**
Romain's feedback was that it was quite difficult to parse the header, so the first solution found was to hardcode the user ID.

As it is not a long term solution, we agreed it was better that each platform provides an URL that takes the header into account.

Another issue will cover how the app simulates a call with the header in order to receive the token.

**Comment by simonLouvet** [comment]
@RachL we could split this issue in 2 : one per platform

**Comment by RachL** [comment]
@simonLouvet yes. Is there anything remaining on Panier Local's side?

**Comment by simonLouvet** [comment]
Panier Local competed
