### ISSUE TITLE
Update OWL file

### ISSUE THREAD

**Issue by RachL** [datafoodconsortium/dfc-prototype-V2#45]
**Description**
This can only be done once the outcomes of #44 have been validated.

Main conclusions: https://docs.google.com/document/d/1PrJaD1daoYqQiai2_JhRhLiusGfaDnkCb7kYeYHgY9I/edit#

**Comment by simonLouvet** [comment]
@RachL you have to Create a "Representation" Class with 4 predicate. 1 realtion to plateform, 1 relation to Thing, 1 Object Property "representByUri", 1 Datatype property "representById"

**Comment by RachL** [comment]
PR to review: https://github.com/datafoodconsortium/ontology/pull/13

**Comment by simonLouvet** [comment]
final solution différent different from this issue : https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=scenarios%20liaison#Uhttps%3A%2F%2Fdrive.google.com%2Fuc%3Fid%3D1_dRstlpHOvG6tCztCwa6dRslUlXcrwf2%26export%3Ddownload
