### ISSUE TITLE
Call OFFacts API to create a product through the semantic bus

### ISSUE THREAD

**Issue by RachL** [datafoodconsortium/dfc-prototype-V2#55]
**Description**
OFFacts API are not semantic API. 

The subject is to get them translated as semantic thanks to the semantic bus.

**Acceptance Tests**
??

**Comment by simonLouvet** [comment]
when a product doesn't exist une OFF and then producer import product from othe platform, when producer want to create a "produit consolidé", proto have to call OFF API (throw Semantic Bus) to crete it and link it whith product from platform
