### ISSUE TITLE
Panier Local's import is not working anymore

### ISSUE THREAD

**Issue by RachL** [datafoodconsortium/dfc-prototype-V2#68]
**Describe the bug**
As seen on demonstration, Panier Local's import is not working anymore.

**Comment by simonLouvet** [comment]
app        | 	at com.local.panier.api.dfc.DfcServlet.service(DfcServlet.java:73)
app        | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
app        | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
app        | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
app        | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
app        | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
app        | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
app        | 	at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:108)
app        | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
app        | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
