### ISSUE TITLE
Provide OFFacts API to create products IDs

### ISSUE THREAD

**Issue by myriamboure** [datafoodconsortium/dfc-prototype-V2#7]
Follow up how it moves forward with Stephane

**Comment by myriamboure** [comment]
Message sent to Stephane on 25/07/2019 on OFFacts slack.

**Comment by myriamboure** [comment]
New message on 05/09/2019, if no answer in a week I'll call.

**Comment by myriamboure** [comment]
Feedack from Stephane saying he will do the API, but didn't manage yet to get a due date. 
![Capture du 2019-09-19 10-41-00](https://user-images.githubusercontent.com/8135376/65228080-1dd10f80-daca-11e9-9a45-1b6256020ef2.png)

Tried to call this morning, left de message.

**Comment by myriamboure** [comment]
Still one sprint where we can do without it, in two weeks we need OFFacts to be ready to work on it as we will need it ready for the next sprint...

**Comment by RachL** [comment]
Blocked by #35
