### ISSUE TITLE
Add a search bar on each product listing

### ISSUE THREAD

**Issue by RachL** [datafoodconsortium/dfc-prototype-V2#71]
**Description**
Searching for a product is currently difficult, therefore we need to introduce search bars.

2 pages would currently need those:
1. `/x-catalog-import`
2. `/x-catalog-supply`

The search bar would work as an auto-completion field: after typing some letters, suggestions are poping up.

The current workflow: first selecting the product, then the action button would remain untouched.

**Acceptance Tests**
1. Go to  `/x-catalog-import`
2. Use the search bar
3. Check you can select a product and use the action button easily

Repeat this scenario with the `/x-catalog-supply` page.

**Mockups**
The search bar should be put **left of the action buttons, on the same line.** The Title of the page would remain above everything.

![image](https://user-images.githubusercontent.com/6525576/73210204-1097f180-414a-11ea-8bbe-f3539853330e.png)

**Comment by simonLouvet** [comment]
@RachL Je pense que l'usage le plus utile du filtre est lors de la réconciliation (liaison des produit entre eux). Je peux l’implémenter pour le catalogue et la liste des import à réconcilier mais le plus utile le semble vraiment sur x-item-import.
![image](https://user-images.githubusercontent.com/5068825/73986188-42c10480-493d-11ea-83e2-f2bde04fe347.png)

J'ai laissé un bouton de filtrage pour des question d'ergonomie. Si je filtre directement, le user ne voie rien dans les produit qu'il peut réconcilier et pense qu'il y a un bug.

J'en este la ou je l'implémente ou tu le souhaitais?

**Comment by RachL** [comment]
@simonLouvet ok pour le bouton. Pour les pages, je pense que c'est utile sur le catalogue final. En démo souvent on galère à montrer ensuite que la consolidation s'est bien passée. Ok pour toi ? Sur la page initial ok pour ne pas le mettre.

**Comment by simonLouvet** [comment]
> 'est utile sur le catalogue final.

ok :-)
