### ISSUE TITLE
How to add metadata to the ontology with protege?

### ISSUE THREAD

**Issue by RachL** [datafoodconsortium/dfc-prototype-V2#72]
As described here: https://github.com/datafoodconsortium/ontology/issues/10#issuecomment-533498058

We need to add metadata (title, description, authors, version, publishers, etc) to our ontology in order to publish it on LOV.

The trick is to find how to do this with Protege...

**Comment by simonLouvet** [comment]
https://lov.linkeddata.es/Recommendations_Vocabulary_Design.pdf
