### ISSUE TITLE
OWL where each concept is in file

### ISSUE THREAD

**Issue by simonLouvet** [datafoodconsortium/dfc-prototype-V2#76]
**Is your feature request related to a problem? Please describe.**
some part of models arne't in good file (full model instead specific model).

**Describe the solution you'd like**
file review by an expert

**Describe alternatives you've considered**
keep ugly files

**Additional context**
It isn't easy to know where is each concpt in protege

**Comment by RachL** [comment]
@simonLouvet is this something we want to talk with Thomas as well? I've created an issue for the other topics: https://github.com/datafoodconsortium/dfc-prototype-V3/issues/1
