### ISSUE TITLE
deconnect from lescommuns.org

### ISSUE THREAD

**Issue by simonLouvet** [datafoodconsortium/dfc-prototype-V2#79]
**Is your feature request related to a problem? Please describe.**
deconnect from lescommuns.org

**Describe the solution you'd like**
a button in profile page to deconnet from lescommuns.org

**Describe alternatives you've considered**

**Additional context**

**Comment by RachL** [comment]
@simonLouvet Merci Simon, désolée je suis trop à la bourre sur le CR :/
