### ISSUE TITLE
Fix bug on Open Food France & update according to new API template

### ISSUE THREAD

**Issue by RachL** [datafoodconsortium/dfc-prototype-V2#86]
**Describe the bug**

Fix bugs on importing products from Open Food France in the DFC prototype.

+ update the API template to fit the new template: https://datafoodconsortium.gitbook.io/dfc-standard-documentation/technical-specification/api-examples

Some fields are missing in the OFN model, but that ok, we can just return empty fields.

**Comment by RachL** [comment]
PR on OFN is here: https://github.com/openfoodfoundation/openfoodnetwork/issues/5810

**Comment by simonLouvet** [comment]
DONE
Platform configuration in config file
Platform management inside semantic store
Plaform well used (business server) and well repsent (interace)

1J

**Comment by RachL** [comment]
@pacodelaluna so it seems to work well except the only products to be fetched are potatoes 🤣  Yet the producer TestDFC in prod has products, but no potatoes 🙈 When you will get back to this let's test together before launching the work on 1.4.

**Comment by RachL** [comment]
@simonLouvet it works now! 🎉 We created 2 tests enterprises by mistake. All fixed.

![image](https://user-images.githubusercontent.com/6525576/98968195-a7813f00-250d-11eb-9528-01edadd986e3.png)
